messages:
  you_dont_have_permission: '&8(&bРП&8) &7У вас недостаточно прав для использования этой команды!'
  bad_usage_me: '&8(&bРП&8) &7Вы ничего не ввели, использование команды: &6/me <текст>'
  bad_usage_do: '&8(&bРП&8) &7Вы ничего не ввели, использование команды: &6/do <текст>'
  bad_usage_try: '&8(&bРП&8) &7Вы ничего не ввели, использование команды: &6/try <текст>'
  reload: '&8(&bРП&8) &7Конфигурация плагина успешно перезагружена!'
  commands:
    me: '&f* &7%player% %text%&f *'
    do: '&f* &7%text%&f *'
    try: '&f* &7%player% %text%&f &8[%result%&8] &f*'
radius:
  me: 20
  try: 20
  do: 20